language: node_js
node_js:
  - 13

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH

install: yarn install

script:
  - 'yarn test:ci'

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master
